import os
import sys

import Metashape
import Metashape as ms

from utils import get_arg, report_progress, get_chunk, rb, extend_file_name


def export_orthomosaic(psx_file, ortho_file, chunk_lab, coordinate_system, background_color, write_kml,
                       write_world_file, write_tile_scheme, image_description, write_tiled_tiff,
                       generate_tiff_overviews, write_big_tiff_file, save_alpha_channel, tiff_compression,
                       jpeg_quality, batch):

    doc = ms.Document()

    doc.open(path=psx_file, read_only=False, ignore_lock=True)

    chunk = get_chunk(doc.chunks, chunk_lab)

    ortho_file = extend_file_name(ortho_file, chunk_lab)

    compression = Metashape.ImageCompression()
    compression.tiff_tiled = rb(write_tiled_tiff)
    compression.tiff_overviews = rb(generate_tiff_overviews)

    if tiff_compression == "LZW":
        compression.tiff_compression = ms.ImageCompression.TiffCompressionLZW
    elif tiff_compression == "JPEG":
        compression.tiff_compression = ms.ImageCompression.TiffCompressionJPEG
    elif tiff_compression == "Packbits":
        compression.tiff_compression = ms.ImageCompression.TiffCompressionPackbits
    elif tiff_compression == "Deflate":
        compression.tiff_compression = ms.ImageCompression.TiffCompressionDeflate
    else:
        compression.tiff_compression = ms.ImageCompression.TiffCompressionLZW

    compression.jpeg_quality = int(jpeg_quality)
    compression.tiff_big = True


    if background_color == "White":
        white_background_mode = True
    else:
        white_background_mode = False

    batch = rb(batch)

    if chunk is not None:
        if not batch and os.path.exists(ortho_file):
            print("vd: This Orthomosaic file already exists!~For this chunk, a Orthomosaic was already exported which cannot be overwritten.~Please remove the current Orthomosaic.")
            print("vn:EXPORT_ORTHOMOSAIC:false")
        else:
            projection = Metashape.OrthoProjection()
            projection.crs = ms.CoordinateSystem(coordinate_system)

            if chunk.orthomosaic is not None:
                chunk.exportRaster(
                    path=ortho_file,
                    format=Metashape.RasterFormatTiles,
                    image_format=Metashape.ImageFormatNone,
                    raster_transform=Metashape.RasterTransformNone,
                    projection=projection,
                    # [, region ],
                    resolution=0,
                    resolution_x=0,
                    resolution_y=0,
                    block_width=10000,
                    block_height=10000,
                    split_in_blocks=False,  # set to True if export fails because data too large
                    width=0,
                    height=0,
                    # [, world_transform ],
                    nodata_value=-32767,
                    save_kml=rb(write_kml),
                    save_world=rb(write_world_file),
                    save_scheme=rb(write_tile_scheme),
                    save_alpha=rb(save_alpha_channel),
                    image_description=image_description,
                    image_compression=compression,
                    network_links=True,
                    global_profile=False,
                    min_zoom_level=-1,
                    max_zoom_level=-1,
                    white_background=white_background_mode,
                    clip_to_boundary=True,
                    title='Orthomosaic',
                    description='Generated by Agisoft Metashape',
                    source_data=ms.OrthomosaicData,
                    # options: TiePointsData, PointCloudData, DepthMapsData, ModelData, TiledModelData, ElevationData, OrthomosaicData, ImagesData
                    north_up=True,
                    tile_width=256,
                    tile_height=256,
                    progress=report_progress
                )

                doc.save()

                print("vn:EXPORT_ORTHOMOSAIC:true")

            else:
                print("vn:EXPORT_ORTHOMOSAIC:false")

    else:
        print("vn:EXPORT_ORTHOMOSAIC:false")

    del doc


if __name__ == '__main__':
    args = sys.argv[1:]

    project_file = get_arg(args, "-psxFile")
    target_file = get_arg(args, "-orthoFile")
    chunk_label = get_arg(args, "-chunk_label")
    batch_edit = get_arg(args, "-batch")

    coordinate_system = get_arg(args, "-coordinatesystem")
    background_color = get_arg(args, "-backgroundcolor")
    write_kml = get_arg(args, "-writekml")
    write_world_file = get_arg(args, "-writeworldfile")
    write_tile_scheme = get_arg(args, "-writetilescheme")
    image_description = get_arg(args, "-imagedescription")
    write_tiled_tiff = get_arg(args, "-writetiledtiff")
    generate_tiff_overviews = get_arg(args, "-generatetiffoverviews")
    write_big_tiff_file = get_arg(args, "-writebigtifffile")
    save_alpha_channel = get_arg(args, "-savealphachannel")
    tiff_compression = get_arg(args, "-tiffcompression")
    jpeg_quality = get_arg(args, "-jpegquality")

    export_orthomosaic(project_file, target_file, chunk_label, coordinate_system, background_color, write_kml,
                       write_world_file, write_tile_scheme, image_description, write_tiled_tiff,
                       generate_tiff_overviews, write_big_tiff_file, save_alpha_channel, tiff_compression,
                       jpeg_quality, batch_edit)
