import os
import sys

import Metashape
import Metashape as ms

from utils import get_arg, report_progress, get_chunk


def export_orthomosaic(psx_file, ortho_file, chunk_lab):
    doc = ms.Document()

    doc.open(path=psx_file, read_only=False, ignore_lock=True)

    chunk = get_chunk(doc.chunks, chunk_lab)

    if chunk is not None:
        if os.path.exists(ortho_file):
            print("vd: This ORTHOMOSAIC file already exists!")
            del doc
        else:
            if chunk.orthomosaic is not None:
                chunk.exportRaster(
                    path=ortho_file,
                    format=Metashape.RasterFormatTiles,
                    image_format=Metashape.ImageFormatNone,
                    raster_transform=Metashape.RasterTransformNone,
                    # [, projection ]
                    # [, region ],
                    resolution=0,
                    resolution_x=0,
                    resolution_y=0,
                    block_width=10000,
                    block_height=10000,
                    split_in_blocks=False,  # set to True if export fails because data too large
                    width=0,
                    height=0,
                    # [, world_transform ],
                    nodata_value=-32767,
                    save_kml=False,
                    save_world=False,
                    save_scheme=False,
                    save_alpha=False,  # changed to False
                    image_description='',
                    # image_compression = compression,
                    network_links=True,
                    global_profile=False,
                    min_zoom_level=-1,
                    max_zoom_level=-1,
                    white_background=True,
                    clip_to_boundary=True,
                    title='Orthomosaic',
                    description='Generated by Agisoft Metashape',
                    source_data=Metashape.OrthomosaicData,
                    # options: TiePointsData, PointCloudData, DepthMapsData, ModelData, TiledModelData, ElevationData, OrthomosaicData, ImagesData
                    north_up=True,
                    tile_width=256,
                    tile_height=256,
                    progress=report_progress
                )

                doc.save()

                print("vn:EXPORT_ORTHOMOSAIC:true")

            else:
                print("vn:EXPORT_ORTHOMOSAIC:false")

    else:
        print("vn:EXPORT_ORTHOMOSAIC:false")

    del doc


if __name__ == '__main__':
    args = sys.argv[1:]

    project_file = get_arg(args, "-psxFile")
    target_file = get_arg(args, "-orthoFile")
    chunk_label = get_arg(args, "-chunk_label")

    export_orthomosaic(project_file, target_file, chunk_label)
