import os
import sys

import Metashape
import Metashape as ms

from utils import get_arg, report_progress, get_chunk, rb, extend_file_name


def export_dem(psx_file, dem_file, chunk_lab, coordinate_system, raster_transform, no_data_value, write_kml,
               write_world_file, write_tile_scheme, image_description, write_tiled_tiff, generate_tiff_overviews,
               write_big_tiff_file, batch):

    doc = ms.Document()

    doc.open(path=psx_file, read_only=False, ignore_lock=True)

    chunk = get_chunk(doc.chunks, chunk_lab)

    batch = rb(batch)
    dem_file = extend_file_name(dem_file, chunk_lab)

    if raster_transform == "None":
        raster_transform_mode = ms.RasterTransformNone
    elif raster_transform == "Palette":
        raster_transform_mode = ms.RasterTransformPalette
    else:
        raster_transform_mode = ms.RasterTransformNone

    if chunk is not None:
        if not batch and os.path.exists(dem_file):
            print("ve:This DEM file already exists!~For this chunk, a DEM was already exported which cannot be overwritten.~Please remove the current DEM.")
            print("vn:EXPORT_DEM:false")
        else:
            projection = ms.OrthoProjection()
            projection.crs = ms.CoordinateSystem(coordinate_system)

            if chunk.elevation is not None:
                chunk.exportRaster(
                    path=dem_file,
                    format=Metashape.RasterFormatTiles,
                    image_format=Metashape.ImageFormatNone,
                    raster_transform=raster_transform_mode,
                    projection=projection,
                    # [, region ],
                    resolution=0,
                    resolution_x=0,
                    resolution_y=0,
                    block_width=10000,
                    block_height=10000,
                    split_in_blocks=False,
                    width=0,
                    height=0,
                    # [, world_transform ],
                    nodata_value=no_data_value,
                    save_kml=rb(write_kml),
                    save_world=rb(write_world_file),
                    save_scheme=rb(write_tile_scheme),
                    save_alpha=False,  # changed to False
                    image_description=image_description,
                    # [, image_compression ],
                    network_links=True,
                    global_profile=False,
                    min_zoom_level=-1,
                    max_zoom_level=-1,
                    white_background=True,
                    clip_to_boundary=True,
                    title='Digital Surface Model',
                    description='Generated by Agisoft Metashape',
                    source_data=Metashape.ElevationData,
                    # options: TiePointsData, PointCloudData, DepthMapsData, ModelData, TiledModelData, ElevationData, OrthomosaicData, ImagesData
                    north_up=True,
                    tile_width=256,
                    tile_height=256,
                    progress=report_progress
                )

                doc.save()

                print("vn:EXPORT_DEM:true")

            else:
                print("vn:EXPORT_DEM:false")

    else:
        print("vn:EXPORT_DEM:false")


    del doc


if __name__ == '__main__':
    args = sys.argv[1:]

    project_file = get_arg(args, "-psxFile")
    target_file = get_arg(args, "-demFile")
    chunk_label = get_arg(args, "-chunk_label")
    batch_edit = get_arg(args, "-batch")

    coordinate_system = get_arg(args, "-coordinatesystem")
    raster_transform = get_arg(args, "-rastertransform")
    no_data_value = get_arg(args, "-nodatavalue")
    write_kml = get_arg(args, "-writekml")
    write_world_file = get_arg(args, "-writeworldfile")
    write_tile_scheme = get_arg(args, "-writetilescheme")
    image_description = get_arg(args, "-imagedescription")
    write_tiled_tiff = get_arg(args, "-writetiledtiff")
    generate_tiff_overviews = get_arg(args, "-generatetiffoverviews")
    write_big_tiff_file = get_arg(args, "-writebigtifffile")

    export_dem(project_file, target_file, chunk_label, coordinate_system, raster_transform, no_data_value, write_kml,
               write_world_file, write_tile_scheme, image_description, write_tiled_tiff, generate_tiff_overviews,
               write_big_tiff_file, batch_edit)
