package wue.eorc.umas.enums;

public enum AgisoftTask {

    ADD_PHOTOS,
    ADD_PHOTOS_CHECK,
    SET_BRIGHTNESS,
    SET_BRIGHTNESS_CHECK,
    ALIGN_IMAGES,
    ALIGN_IMAGES_CHECK,
    OPTIMIZE_CAMERAS,
    OPTIMIZE_CAMERAS_CHECK,
    BUILD_POINT_CLOUD,
    BUILD_POINT_CLOUD_CHECK,
    BUILD_DEM,
    BUILD_DEM_CHECK,
    BUILD_ORTHOMOSAIC,
    BUILD_ORTHOMOSAIC_CHECK,
    EXPORT_DEM,
    EXPORT_DEM_CHECK,
    EXPORT_ORTHOMOSAIC,
    EXPORT_ORTHOMOSAIC_CHECK,
    GENERATE_REPORT,
    GENERATE_REPORT_CHECK
}
