package wue.eorc.umas.enums;

public enum Setting {

    UI_THEME,
    FULL_SCREEN_AT_START_UP,
    AGISOFT_EXEC_PATH,
    AGISOFT_VERSION,
    AGISOFT_EXEC_PATH_VALID,
    TERRA_EXEC_PATH,
    TERRA_VERSION,
    TERRA_EXEC_PATH_VALID,
    DATABASE_CONNECTION_STRING,
    DATABASE_CONNECTION_STRING_VALID

}
